server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: first
          predicates:
            - Path=/first/**
          uri: http://localhost:8081
        - id: second
          predicates:
            - Path=/second/**
          uri: http://localhost:8082
        - id: auth-server
          predicates:
            - Path=/login/
          uri: http://localhost:8088

